// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/L2ncE/CloudWeGo-101/api/init"
	"github.com/L2ncE/CloudWeGo-101/api/init/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	r, info := init.InitRegistry()
	rpc.Init()

	h := server.New(
		server.WithHostPorts(fmt.Sprintf(":%d", 8880)),
		server.WithRegistry(r, info),
	)

	register(h)
	h.Spin()
}
