name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: Slash Command Dispatch - Triage
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        reaction-token: ${{ secrets.PAT }}
        repository: L2ncE/github-actions-test
        issue-type: pull-request
        permission: triage
        commands: |
          rebase
          rerun
          rerun-failed

    - name: Slash Command Dispatch - Repo - Triage
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        reaction-token: ${{ secrets.PAT }}
        issue-type: pull-request
        permission: triage
        commands: |
          benchmark

    - name: Slash Command Dispatch - Repo - Write
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        reaction-token: ${{ secrets.PAT }}
        issue-type: pull-request
        permission: write
        commands: |
          land
